/*
 * This file is autogenerated, see util/species-gen.py and dat/species/ for
 * more info.
 */
#pragma once

static species_group species_groups[] =
{

    {
        "Simple",
        coord_def(0, 0),
        20,
        { SP_HILL_ORC, SP_MINOTAUR, SP_MERFOLK, SP_GARGOYLE, SP_BASE_DRACONIAN, SP_HALFLING, SP_TROLL, SP_GHOUL }
    },

    {
        "Intermediate",
        coord_def(25, 0),
        20,
        { SP_HUMAN, SP_HIGH_ELF, SP_KOBOLD, SP_DEMONSPAWN, SP_CENTAUR, SP_SPRIGGAN, SP_TENGU, SP_DEEP_ELF, SP_OGRE, SP_DEEP_DWARF, SP_GNOLL }
    },

    {
        "Advanced",
        coord_def(50, 0),
        20,
        { SP_VINE_STALKER, SP_VAMPIRE, SP_DEMIGOD, SP_FORMICID, SP_NAGA, SP_OCTOPODE, SP_FELID, SP_BARACHI, SP_MUMMY }
    },
};
